/**
 * try-catch
 */
try {
	x();
} catch (e) {
	// try 에서 에러 발생할 경우 실행되는 구문
	console.error(e);
	console.error('에러 발생');
} finally {
	// 어떠한 상황에서도 실행
}
